CHANGELOG.md, README.md, example/README.md, example/mason.yaml, example/todos.json, lib/src/commands/build_command.dart, lib/src/generator.dart, lib/src/version.dart, pubspec.yaml, templates/todos/__template__/todos.md, templates/todos/template.yaml
- feat: support for `--json` option in `mason build` (closes #10)
- feat: support loops in templates (closes #9)
=> feat: support for json and template loops

example/README.md, example/todos.json, example/todos.md, templates/todos/__template__/todos.md
- docs: add example of conditional template logic (closes #6)
=> docs: add example of conditional template logic

CHANGELOG.md, lib/src/generator.dart, lib/src/version.dart, pubspec.yaml
- fix: issue with variable mutation which excluded variables within arrays
=> fix: var mutation which exluded array elements

CHANGELOG.md, README.md, lib/src/command.dart, lib/src/command_runner.dart, lib/src/commands/cache.dart, lib/src/commands/commands.dart, lib/src/logger.dart, lib/src/mason_cache.dart, lib/src/version.dart, pubspec.yaml
- feat: add mason cache clear command
=> feat: add mason cache clear

.github/workflows/main.yaml, .gitignore, pubspec.yaml, test/command_runner_test.dart
- test: add MasonCommandRunner unit tests
=> test: add MasonCommandRunner unit tests

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- feat: add `mason bundle` command
- feat: add `MasonGenerator.fromBundle`
- fix: asset resolution issues
=> chore: v0.0.1-dev.25

.github/workflows/main.yaml, CHANGELOG.md, lib/src/brick_yaml.dart, lib/src/brick_yaml.g.dart, lib/src/bundler.dart, lib/src/command.dart, lib/src/command_runner.dart, lib/src/commands/bundle.dart, lib/src/commands/cache.dart, lib/src/commands/get.dart, lib/src/commands/init.dart, lib/src/commands/make.dart, lib/src/commands/new.dart, lib/src/generator.dart, lib/src/git.dart, lib/src/logger.dart, lib/src/mason_bundle.g.dart, lib/src/mason_cache.dart, lib/src/mason_yaml.dart, lib/src/mason_yaml.g.dart, lib/src/version.dart, pubspec.yaml, test/command_runner_test.dart, test/commands/bundle_test.dart, test/commands/cache_test.dart, test/commands/get_test.dart, test/commands/init_test.dart, test/commands/make_test.dart, test/commands/new_test.dart, test/helpers/directories_deep_equal.dart
- feat: migrate to null safety
=> feat: migrate to null safety

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- feat: add `mason uninstall` command
=> chore: v0.0.1-dev.36

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- feat: add `mason list` command
- docs: update command descriptions for consistency
=> chore: v0.0.1-dev.37

lib/src/commands/make.dart, lib/src/generator.dart, lib/src/logger.dart
- feat: add `OverwriteRule` handling and file diffing to generation
- feat: add `details` api to logger
=> feat: add `OverwriteRule` to handle file conflicts

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- feat: add `OverwriteRule` for file conflict resolution (`Yna`)
- `Y` - overwrite (default)
- `n` - do not overwrite
- `a` - overwrite this an all others
=> chore: v0.0.1-dev.41

lib/src/commands/make.dart, test/command_runner_test.dart, test/commands/make_test.dart, test/helpers/helpers.dart, test/helpers/override_print.dart
=> fix: improve mason make --help

CHANGELOG.md, README.md, lib/src/version.dart, pubspec.yaml
- feat: support partials
Example:
```
├── HELLO.md
├── {{~ footer.md }}
└── {{~ header.md }}
```
`{{~ header.md }}`
```md
```
`{{~ footer.md }}`
```md
_made with 💖 by mason_
```
`HELLO.md`
```md
{{> header.md }}
Hello {{name}}!
{{> footer.md }}
```
`$ mason make hello --name Dash`
`HELLO.md`
```md
Hello Dash!
_made with 💖 by mason_
```
=> chore: v0.0.1-dev.43

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- feat: custom file conflict resolution via `mason make --on-conflict`
=> chore: v0.0.1-dev.44

.github/workflows/main.yaml, README.md
=> docs: add bundle usage to README

.github/workflows/main.yaml
=> ci: use pana v0.19.1

lib/src/bricks_json.dart, lib/src/command_runner.dart, lib/src/commands/get.dart, test/commands/cache_test.dart, test/commands/get_test.dart
**READY**
- fix: mason get ensures brick exists (closes #111)
=> fix: mason get ensures brick exists

lib/src/bricks_json.dart
**READY**
- refactor: use existsSync consistently
=> refactor: use existsSync consistently

lib/src/generator.dart, test/commands/make_test.dart
**READY**
- refactor: adjust append conflict resolution output
=> refactor: adjust append conflict resolution output

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
**READY**
- chore: v0.0.1-dev.48
- feat: add append conflict resolution strategy
- fix: mason get ensures brick exists
- docs: add built-in lambdas section to README
=> chore: v0.0.1-dev.48

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
**READY**
- chore: v0.0.1-dev.49
=> chore: v0.0.1-dev.49

lib/src/commands/get.dart, test/command_runner_test.dart, test/commands/get_test.dart
**READY**
- feat: mason get improve output and command description
=> feat: mason get improve output and command description

lib/src/commands/init.dart, test/commands/init_test.dart, test/fixtures/init/.mason/bricks.json
**READY**
- feat: init command automatically gets first brick
=> feat: init command automatically gets first brick

lib/src/logger.dart
**READY**
- fix: logger stopwatch units
=> fix: logger stopwatch units

lib/src/commands/list.dart, test/commands/list_test.dart
**READY**
- feat: improve mason list empty output
=> feat: improve mason list empty output

lib/src/commands/init.dart, test/fixtures/init/mason.yaml
**READY**
- feat: adjust mason init generated mason.yaml
=> feat: adjust mason init generated mason.yaml

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
**READY**
- chore: v0.0.1-dev.50
- **BREAKING** refactor: remove `mason install` and `mason uninstall`
- `mason install` -> `mason add -g`
- `mason uninstall` -> `mason remove -g`
- feat: adjust `mason init` generated `mason.yaml`
- feat: improve `mason list` empty output
- feat: create `mason remove` command
- feat: create `mason add` command
- feat: `mason init` command automatically gets first brick
- feat: improve output and description for `mason get` command
- fix: logger stopwatch units
- docs: update example/README
=> chore: v0.0.1-dev.50

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
**READY**
- chore: v0.0.1-dev.51
- feat: conditional file and directory creation support
=> chore: v0.0.1-dev.51

lib/src/commands/new.dart, test/commands/new_test.dart
**READY**
- fix: mason new command output format
- use `logger.detail` rather than `logger.success` when flushing output for consistency
=> fix: mason new command output format

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
**READY**
- chore: v0.0.1-dev.56
=> chore: v0.0.1-dev.56

lib/src/commands/bundle.dart, test/commands/bundle_test.dart
**READY**
- feat:(bundle): improve output
=> feat(bundle): improve output

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
**READY**
- chore: v0.0.1-dev.57
=> chore: v0.0.1-dev.57

.github/workflows/mason_cli.yaml, packages/mason_cli/lib/src/command.dart, packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/commands/add_test.dart, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/commands/new_test.dart, packages/mason_cli/test/commands/remove_test.dart, packages/mason_cli/test/src/command_runner_test.dart, packages/mason_cli/test/src/command_test.dart, packages/mason_cli/test/src/yaml_encode_test.dart
**READY**
- test(mason_cli): 100% test coverage
=> test(mason_cli): 100% test coverage

packages/mason_logger/CHANGELOG.md, packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/pubspec.yaml, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- feat(mason_logger): add optional tag to warn
=> feat(mason_logger): add optional tag to warn

packages/mason/CHANGELOG.md, packages/mason/pubspec.yaml
**READY**
- docs(mason): update CHANGELOG and bump logger
=> docs(mason): update CHANGELOG and bump logger

.github/workflows/mason.yaml, packages/mason/coverage_badge.svg, packages/mason/lib/src/bricks_json.dart, packages/mason/pubspec.yaml, packages/mason/test/src/bricks_json_test.dart, packages/mason/test/src/mason_bundle_test.dart
**READY**
- refactor(mason): remove dependency on package:platform
=> refactor(mason): remove dependency on package:platform

packages/mason_cli/CHANGELOG.md, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.2
=> chore(mason_cli): v0.1.0-dev.2

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.3
=> chore(mason_cli): v0.1.0-dev.3

packages/mason/lib/mason.dart, packages/mason/lib/src/generator.dart, packages/mason/lib/src/render.dart, packages/mason/test/src/render_test.dart
**READY**
- feat(mason): expose render apis (closes #150)
=> feat(mason): expose render apis

packages/mason/CHANGELOG.md, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.2
=> chore(mason): v0.1.0-dev.2

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.4
=> chore(mason_cli): v0.1.0-dev.4

packages/mason/lib/src/brick_yaml.dart, packages/mason/lib/src/brick_yaml.g.dart, packages/mason/lib/src/bricks_json.dart, packages/mason/lib/src/mason_bundle.g.dart, packages/mason/lib/src/mason_yaml.g.dart, packages/mason/pubspec.yaml, packages/mason/test/src/brick_yaml_test.dart, packages/mason/test/src/generator_test.dart, packages/mason_cli/pubspec.yaml
**READY**
- feat(mason)!: add version to brick.yaml
=> feat(mason)!: add version to brick.yaml

packages/mason_cli/lib/src/commands/init.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/fixtures/init/bricks/hello/brick.yaml, packages/mason_cli/test/fixtures/new/bricks/hello_world/brick.yaml
**READY**
- feat(mason_cli)!: add versions to newly created bricks
- `mason init`
- `mason new <BRICK_NAME>`
=> feat(mason_cli)!: add versions to newly created bricks

.github/workflows/mason.yaml, .github/workflows/mason_cli.yaml, packages/mason/lib/src/bundler.dart, packages/mason/pubspec.yaml, packages/mason/test/src/bundler_test.dart
**READY**
- fix(mason): bundle file sort order (closes #185)
=> fix(mason): bundle file sort order

packages/mason/CHANGELOG.md, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.3
=> chore(mason): v0.1.0-dev.3

packages/mason_cli/CHANGELOG.md, packages/mason_cli/README.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.5
=> chore(mason_cli): v0.1.0-dev.5

packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/test/commands/add_test.dart, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/cache_test.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/init_test.dart, packages/mason_cli/test/commands/list_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/commands/new_test.dart, packages/mason_cli/test/commands/remove_test.dart
**READY**
- feat(mason_cli): add validation to BrickVariableType.number inputs
- test(mason_cli): increase test speed by mocking `PubUpdater` in all relevant suites.
=> feat(mason_cli): add validation to BrickVariableType.number inputs

packages/mason/lib/src/bundler.dart, packages/mason/lib/src/mason_bundle.dart, packages/mason/lib/src/mason_bundle.g.dart, packages/mason/test/bundles/greeting_bundle.dart, packages/mason/test/bundles/hooks_bundle.dart, packages/mason/test/bundles/photos_bundle.dart, packages/mason/test/src/mason_bundle_test.dart
**READY**
- feat(mason)!: add brick version to bundle
=> feat(mason)!: add brick version to bundle

packages/mason/lib/src/generator.dart, packages/mason/test/src/generator_test.dart
**READY**
- fix(mason): ignore FileConflictResolution when there are no conflicts
- closes #196
=> fix(mason): ignore FileConflictResolution when there are no conflicts

packages/mason_cli/lib/src/commands/init.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/fixtures/init/bricks/hello/brick.yaml, packages/mason_cli/test/fixtures/new/bricks/hello_world/brick.yaml
**READY**
- feat(mason_cli): enhance brick generated by mason new/init
=> feat(mason_cli): enhance brick generated by mason new/init

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- fix(mason_logger): prompt w/out default fix spacing
=> fix(mason_logger): prompt w/out default fix spacing

bricks/app_icon/brick.yaml, bricks/bio/brick.yaml, bricks/documentation/brick.yaml, bricks/greeting/brick.yaml, bricks/hello_world/brick.yaml, bricks/hooks/brick.yaml, bricks/photos/brick.yaml, bricks/plugin/brick.yaml, bricks/simple/brick.yaml, bricks/todos/brick.yaml, bricks/widget/brick.yaml, packages/mason/test/src/generator_test.dart, packages/mason_cli/README.md, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/make_test.dart
**READY**
- refactor(mason): upgrade example bricks and README
=> refactor(mason): upgrade example bricks and README

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- feat(mason_logger): improve progress time style
- fix(mason_logger): progress/update string truncation
=> feat(mason_logger): improve progress time style

packages/mason_logger/README.md, packages/mason_logger/example/main.dart
**READY**
- docs(mason_logger): update example and README
=> docs(mason_logger): update example and README

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- fix: `progress` string truncation
- feat: add `confirm`
- feat: add `defaultValue` to `prompt`
- feat: improve `progress` time style
- docs: update example and `README`
=> chore(mason_logger): v0.1.0-dev.4

packages/mason/CHANGELOG.md, packages/mason/pubspec.yaml
**READY**
- **BREAKING** feat: restructure `brick.yaml` vars to support type, description, and default:
```yaml
name: example
description: An example brick.
version: 0.1.0+1
vars:
name:
type: string
description: Your name
default: Dash
prompt: What is your name?
```
- **BREAKING** feat: add `version` to bundle
- **BREAKING** refactor: API improvements to `MasonBundle`, `MasonGenerator`, and `DirectoryGeneratorTarget`
- `MasonBundle`
- Use named constructor parameters instead of positional parameters
- `MasonGenerator.generate(...)`
- Accepts optional `Logger` and `FileConflictResolution`
- `DirectoryGeneratorTarget`
- No longer accepts optional `Logger` and `FileConflictResolution` (moved to `generate` API above)
**Before**
```dart
final generator = MasonGenerator.fromBundle(myBundle); …
```
=> chore(mason): v0.1.0-dev.4

packages/mason_cli/lib/src/commands/list.dart, packages/mason_cli/test/commands/list_test.dart
**READY**
- feat(mason_cli): mason ls alphabetical sort order
=> feat(mason_cli): mason ls alphabetical sort order

bricks/hooks/hooks/pubspec.yaml, bricks/random_color/hooks/pubspec.yaml, packages/mason/test/bundles/hooks_bundle.dart, packages/mason/test/fixtures/execution_exception/hooks/pubspec.yaml, packages/mason/test/fixtures/missing_run/hooks/pubspec.yaml, packages/mason/test/fixtures/run_exception/hooks/pubspec.yaml, packages/mason/test/fixtures/unicode_hook/hooks/pubspec.yaml
**READY**
- chore: adjust hook mason refs
=> chore: adjust hook mason refs

packages/mason/CHANGELOG.md, packages/mason/pubspec.yaml
**READY**
- **BREAKING** feat: add computed vars support via `HookContext`
```dart
// pre_gen.dart
import 'package:mason/mason.dart';
// Every hook must contain a run method which accepts a `HookContext`
// from package:mason/mason.dart.
void run(HookContext context) {
// Read/Write vars
context.vars = {...context.vars, 'custom_var': 'foo'};
// Use the logger
context.logger.info('hello from pre_gen.dart');
}
```
=> chore(mason): v0.1.0-dev.5

packages/mason_cli/README.md, packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/lib/src/commands/commands.dart, packages/mason_cli/lib/src/commands/update.dart, packages/mason_cli/test/commands/update_test.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- feat(mason_cli): add update command and remove auto update prompt (closes #218)
=> feat(mason_cli): add update command and remove auto update prompt

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- feat: add `mason update` command
- feat: remove auto-update prompt when never version exists
- docs: minor updates to CLI description and README
=> chore(mason_cli): v0.1.0-dev.8

packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/bundle_test.dart
**READY**
- feat(bundle): apply bzip2 compression
=> feat(bundle): apply bzip2 compression

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.9
=> chore(mason_cli): v0.1.0-dev.9

packages/mason/analysis_options.yaml, packages/mason/build.yaml, packages/mason/lib/mason.dart, packages/mason/lib/src/version.dart
**READY**
- feat(mason): expose packageVersion constant
=> feat(mason): expose packageVersion constant

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.6
=> chore(mason): v0.1.0-dev.6

.github/workflows/mason_cli.yaml, packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/lib/src/commands/update.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/add_test.dart, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/cache_test.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/init_test.dart, packages/mason_cli/test/commands/list_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/commands/new_test.dart, packages/mason_cli/test/commands/remove_test.dart, packages/mason_cli/test/commands/update_test.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- chore(mason_cli): upgrade to mason 0.1.0-dev.6
=> chore(mason_cli): upgrade to mason 0.1.0-dev.6

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.10
=> chore(mason_cli): v0.1.0-dev.10

.github/workflows/mason.yaml, .github/workflows/mason_cli.yaml, .github/workflows/mason_logger.yaml
**READY**
- ci: upgrade to very_good_coverage@v1
=> ci: upgrade to very_good_coverage@v1

packages/mason/CHANGELOG.md, packages/mason/lib/src/bricks_json.dart, packages/mason/test/src/bricks_json_test.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/commands/remove_test.dart
**READY**
- refactor(mason)!: simplify bricks.json format
=> refactor(mason)!: simplify bricks.json format

packages/mason/lib/src/brick.dart, packages/mason/test/src/bricks_json_test.dart, packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/lib/src/commands/new.dart
**READY**
- refactor(mason): Brick.path requires brick name
=> refactor(mason): Brick.path requires brick name

packages/mason/lib/src/brick.dart, packages/mason/lib/src/bricks_json.dart, packages/mason/test/src/bricks_json_test.dart, packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/lib/src/commands/new.dart
**READY**
- refactor(mason): make brick name optional in Brick class
=> refactor(mason): make brick name optional in Brick class

packages/mason/CHANGELOG.md, packages/mason/lib/src/bricks_json.dart, packages/mason/test/src/bricks_json_test.dart, packages/mason_cli/CHANGELOG.md, packages/mason_cli/README.md, packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/lib/src/version.dart, packages/mason_cli/lib/src/yaml_encode.dart, packages/mason_cli/test/commands/add_test.dart, packages/mason_cli/test/commands/list_test.dart, packages/mason_cli/test/commands/remove_test.dart, packages/mason_cli/test/src/yaml_encode_test.dart
**READY**
```sh
mason add my_brick
mason add --global my_brick
mason add -g my_brick
mason add my_brick --path ./path/to/my_brick
mason add --global my_brick --path ./path/to/my_brick
mason add -g my_brick --path ./path/to/my_brick
mason add my_brick --git-url https://github.com/org/repo
mason add -g my_brick --git-url https://github.com/org/repo
mason add my_brick --git-url https://github.com/org/repo --git-path path/to/my_brick
mason add my_brick --git-url https://github.com/org/repo --git-path path/to/my_brick --git-ref tag-name
```
=> feat(mason_cli)!: mason add support for hosted bricks

packages/mason/CHANGELOG.md, packages/mason/README.md, packages/mason/example/main.dart, packages/mason/lib/src/generator.dart, packages/mason/test/src/generator_test.dart, packages/mason/test/src/hooks_test.dart, packages/mason_cli/lib/src/commands/make.dart
**READY**
- refactor(mason)!: MasonGenerator.fromBrick
=> refactor(mason)!: MasonGenerator.fromBrick

.github/workflows/mason_auth.yaml, packages/mason_auth/.gitignore, packages/mason_auth/CHANGELOG.md, packages/mason_auth/LICENSE, packages/mason_auth/README.md, packages/mason_auth/analysis_options.yaml, packages/mason_auth/build.yaml, packages/mason_auth/coverage_badge.svg, packages/mason_auth/example/main.dart, packages/mason_auth/lib/mason_auth.dart, packages/mason_auth/lib/src/jwt_decode.dart, packages/mason_auth/lib/src/mason_auth.dart, packages/mason_auth/lib/src/models/credentials.dart, packages/mason_auth/lib/src/models/credentials.g.dart, packages/mason_auth/lib/src/models/models.dart, packages/mason_auth/lib/src/models/user.dart, packages/mason_auth/pubspec.yaml, packages/mason_auth/test/src/jwt_decode_test.dart, packages/mason_auth/test/src/mason_auth_test.dart
**READY**
- feat(mason_auth): create package:mason_auth
=> feat(mason_auth): create package:mason_auth

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- feat(mason_logger): add hidden flag to prompt
=> feat(mason_logger): add hidden flag to prompt

packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/lib/src/commands/commands.dart, packages/mason_cli/lib/src/commands/login.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/login_test.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- feat(mason_cli): add `mason login` command
=> feat(mason_cli): add mason login command

packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/lib/src/commands/commands.dart, packages/mason_cli/lib/src/commands/logout.dart, packages/mason_cli/test/commands/login_test.dart, packages/mason_cli/test/commands/logout_test.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- feat(mason_cli): add `mason logout` command
=> feat(mason_cli): add mason logout command

packages/mason/lib/src/bricks_json.dart, packages/mason/test/src/bricks_json_test.dart
**READY**
- refactor(mason): convert hostedUrl to hostedUri
=> refactor(mason): convert hostedUrl to hostedUri

packages/mason/lib/src/bricks_json.dart
**READY**
- refactor(mason): refactor git cache directory location
=> refactor(mason): refactor git cache directory location

packages/mason/lib/mason.dart, packages/mason/lib/src/bricks_json.dart, packages/mason/lib/src/path.dart, packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/lib/src/commands/list.dart, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/lib/src/version.dart, packages/mason_cli/test/commands/add_test.dart, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/list_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/commands/remove_test.dart
**READY**
- feat(mason_cli): add brick source to mason list
```
$ mason ls
/Users/felangel/Development/playgrounds/mason_playground
├── greeting 0.1.0+2 -> registry.brickhub.dev
├── simple 0.1.0+1 -> /local/path/to/simple
└── widget 0.1.0+1 -> https://github.com/felangel/mason#997bc878c93534fad17d965be7cafe948a1dbb53
```
=> feat(mason_cli): add brick source to mason list

packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- fix(mason_cli): simplify update prompt styling
=> fix(mason_cli): simplify update prompt styling

packages/mason_auth/lib/mason_auth.dart, packages/mason_auth/lib/src/mason_auth.dart, packages/mason_auth/test/src/mason_auth_test.dart
**READY**
- feat(mason_auth): add publish
=> feat(mason_auth): add publish

packages/mason_api/lib/src/mason_api.dart, packages/mason_api/test/src/mason_api_test.dart
**READY**
- feat(mason_api): support custom hosted uri
=> feat(mason_api): support custom hosted uri

packages/mason_cli/lib/src/command_runner.dart
**READY**
- refactor(mason_cli): use hosted uri
=> refactor(mason_cli): use hosted uri

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.2
=> chore(mason_api): v0.1.0-dev.2

packages/mason_cli/lib/src/commands/publish.dart, packages/mason_cli/test/commands/publish_test.dart
**READY**
- feat(mason_cli): add publish prompt/alert
=> feat(mason_cli): add publish prompt/alert

.github/workflows/mason_logger.yaml, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): upgrade to Dart 2.16
=> chore(mason_logger): upgrade to Dart 2.16

.github/workflows/mason_api.yaml, packages/mason_api/pubspec.yaml, packages/mason_api/test/src/mason_api_test.dart
**READY**
- chore(mason_api): upgrade to Dart 2.16
=> chore(mason_api): upgrade to Dart 2.16

.github/workflows/mason.yaml, packages/mason/lib/src/generator.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): upgrade to Dart 2.16
=> chore(mason): upgrade to Dart 2.16

.github/workflows/mason_cli.yaml, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/login_test.dart, packages/mason_cli/test/commands/logout_test.dart, packages/mason_cli/test/commands/publish_test.dart
**READY**
- chore(mason_cli): upgrade to Dart 2.16
=> chore(mason_cli): upgrade to Dart 2.16

packages/mason/lib/src/compute.dart, packages/mason/lib/src/mason_bundle.dart, packages/mason/test/src/compute_test.dart, packages/mason/test/src/mason_bundle_test.dart
**READY**
- refactor(mason)!: MasonBundle.toUniversalBundle run in Isolate
=> refactor(mason)!: MasonBundle.toUniversalBundle run in Isolate

packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/lib/src/commands/publish.dart
**READY**
- refactor(mason_cli): use async toUniversalBundle
=> refactor(mason_cli): use async toUniversalBundle

packages/mason_cli/lib/src/command.dart, packages/mason_cli/lib/src/commands/publish.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/publish_test.dart
**READY**
- feat(mason_cli): verify bundle size before publish
=> feat(mason_cli): verify bundle size before publish

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.3
=> chore(mason_api): v0.1.0-dev.3

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.0-dev.5
=> chore(mason_logger): v0.1.0-dev.5

packages/mason/CHANGELOG.md, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.7
=> chore(mason): v0.1.0-dev.7

packages/mason_cli/CHANGELOG.md, packages/mason_cli/README.md, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.11
=> chore(mason_cli): v0.1.0-dev.11

packages/mason/lib/mason.dart, packages/mason/lib/src/brick_yaml.dart, packages/mason/lib/src/brick_yaml.g.dart, packages/mason/lib/src/bundler.dart, packages/mason/lib/src/mason_bundle.dart, packages/mason/lib/src/mason_bundle.g.dart, packages/mason/test/src/bundler_test.dart, packages/mason/test/src/mason_bundle_test.dart
**READY**
- feat(mason): add environment to brick.yaml
=> feat(mason): add environment to brick.yaml

packages/mason_cli/lib/src/commands/init.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/publish_test.dart, packages/mason_cli/test/fixtures/init/bricks/hello/brick.yaml, packages/mason_cli/test/fixtures/new/bricks/hello_world/brick.yaml
**READY**
- feat(mason_cli): support brick environment
=> feat(mason_cli): support brick environment

packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/make_test.dart
**READY**
- feat(mason_cli): mason make verifies brick supports current mason ver…
=> feat(mason_cli): mason make verify brick supports current mason version

packages/mason/lib/mason.dart, packages/mason/lib/src/brick_compatibility.dart, packages/mason/lib/src/bricks_json.dart, packages/mason/test/src/brick_compatibility_test.dart, packages/mason/test/src/bricks_json_test.dart, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/make_test.dart
**READY**
- feat(mason): add `isBrickCompatibleWithMason`
=> feat(mason): add isBrickCompatibleWithMason

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.8
=> chore(mason): v0.1.0-dev.8

.github/workflows/mason_cli.yaml, packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.12
=> chore(mason_cli): v0.1.0-dev.12

packages/mason_cli/lib/src/commands/list.dart, packages/mason_cli/test/commands/list_test.dart
**READY**
- fix(mason_cli): mason list git path parsing
=> fix(mason_cli): mason list git path parsing

packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/test/commands/bundle_test.dart
**READY**
- feat(mason_cli): improve stdout for mason bundle
=> feat(mason_cli): improve stdout for mason bundle

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.13
=> chore(mason_cli): v0.1.0-dev.13

packages/mason/lib/mason.dart, packages/mason/lib/src/bundler.dart, packages/mason/lib/src/generator.dart, packages/mason/test/src/mason_bundle_test.dart
**READY**
- feat: expose `MasonBundledFile`
=> feat: expose MasonBundledFile

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.9
=> chore(mason): v0.1.0-dev.9

packages/mason_cli/README.md
**READY**
- docs(mason_cli): update unbundle docs in README
=> docs(mason_cli): update unbundle docs in README

packages/mason/lib/src/bricks_json.dart, packages/mason/lib/src/mason_bundle.dart, packages/mason/test/src/mason_bundle_test.dart, packages/mason_cli/test/commands/bundle_test.dart
**READY**
- feat(mason)!: convert `MasonBundle.fromUniversalBundle` to async and perform decode in Isolate.
=> feat(mason)!: use async fromUniversalBundle

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- **BREAKING**: feat: run `fromUniversalBundle` in `Isolate` (async)
- feat: expose `Yaml` encoding utility
- feat: add `fromDartBundle` to `MasonBundle`
=> chore(mason): v0.1.0-dev.10

packages/mason/lib/src/yaml_encode.dart, packages/mason/test/src/yaml_encode_test.dart
**READY**
- fix(mason): yaml.encode handle escape characters
=> fix(mason): yaml.encode handle escape characters

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.11
=> chore(mason): v0.1.0-dev.11

packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/fixtures/new/bricks/hello_world/brick.yaml
**READY**
- feat(mason_cli): add inline comments to new brick.yaml
=> feat(mason_cli): add inline comments to new brick.yaml

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.15
=> chore(mason_cli): v0.1.0-dev.15

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.12
=> chore(mason): v0.1.0-dev.12

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.0-dev.6
=> chore(mason_logger): v0.1.0-dev.6

packages/mason_api/lib/src/mason_api.dart, packages/mason_api/test/src/mason_api_test.dart
**READY**
- feat(mason_api): add details to MasonApiException
=> feat(mason_api): add details to MasonApiException

packages/mason_api/lib/src/mason_api.dart, packages/mason_api/lib/src/models/error_response.dart, packages/mason_api/lib/src/models/error_response.g.dart, packages/mason_api/lib/src/models/models.dart, packages/mason_api/test/src/mason_api_test.dart
**READY**
- refactor(mason_api): define ErrorResponse w/JsonSerializable
=> refactor(mason_api): define ErrorResponse w/JsonSerializable

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.4
=> chore(mason_api): v0.1.0-dev.4

packages/mason_cli/lib/src/commands/publish.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/publish_test.dart
**READY**
- feat(mason_cli): upgrade to mason_api v0.1.0-dev.4
=> feat(mason_cli): upgrade to mason_api v0.1.0-dev.4

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.16
=> chore(mason_cli): v0.1.0-dev.16

packages/mason_cli/lib/src/commands/init.dart, packages/mason_cli/test/fixtures/init/mason.yaml
**READY**
- chore(mason_cli): use fixed version of hello brick in mason init
=> chore(mason_cli): use fixed version of hello brick in mason init

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.17
=> chore(mason_cli): v0.1.0-dev.17

packages/mason/lib/mason.dart, packages/mason/lib/src/brick_compatibility.dart, packages/mason/lib/src/bricks_json.dart, packages/mason/lib/src/generator.dart, packages/mason/lib/src/mason_lock_json.dart, packages/mason/lib/src/mason_lock_json.g.dart, packages/mason/test/src/bricks_json_test.dart, packages/mason/test/src/mason_lock_json_test.dart
**READY**
- **BREAKING**: feat: `BricksJson.add` returns `CachedBrick` instead of `String` location.
- feat: add `MasonLockJson`
- feat: export `CachedBrick`, `MasonLockJson`, `Version`, `VersionConstraint`, and `VersionRange`
=> feat(mason)!: add MasonLockJson

packages/mason/lib/mason.dart
**READY**
- chore(mason): expose GeneratorHooks
=> chore(mason): expose GeneratorHooks

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.13
=> chore(mason): v0.1.0-dev.13

.github/workflows/mason_cli.yaml, packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.18
=> chore(mason_cli): v0.1.0-dev.18

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.0-dev.7
=> chore(mason_logger): v0.1.0-dev.7

bricks/greeting/brick.yaml, bricks/hello/brick.yaml, packages/mason/lib/src/brick_yaml.dart, packages/mason/lib/src/brick_yaml.g.dart, packages/mason/lib/src/bundler.dart, packages/mason/lib/src/mason_bundle.dart, packages/mason/lib/src/mason_bundle.g.dart, packages/mason/test/src/brick_yaml_test.dart, packages/mason/test/src/bundler_test.dart, packages/mason/test/src/mason_bundle_test.dart
**READY**
- feat(mason): add optional repository field to brick.yaml
=> feat(mason): add optional repository field to brick.yaml

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.14
=> chore(mason): v0.1.0-dev.14

packages/mason_cli/README.md
**READY**
Adds note to descibe what should and can be excluded from version control in `packages/mason_cli/README.md`
=> docs(mason_cli): add note regarding .mason and mason-lock.json

packages/mason_cli/lib/src/commands/publish.dart, packages/mason_cli/test/commands/publish_test.dart
**READY**
- chore(mason_cli): add policy details on publish
=> chore(mason_cli): add policy details on publish

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.19
=> chore(mason_cli): v0.1.0-dev.19

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.20
=> chore(mason_cli): v0.1.0-dev.20

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- fix(mason_logger): previous line overwrite on single-line prompts
=> fix(mason_logger): previous line overwrite on single-line prompts

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.0-dev.8
=> chore(mason_logger): v0.1.0-dev.8

packages/mason_cli/CHANGELOG.md, packages/mason_cli/README.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.21
=> chore(mason_cli): v0.1.0-dev.21

packages/mason/pubspec.yaml
**READY**
- chore(mason): use mason_logger ^0.1.0-dev.8
=> chore(mason): use mason_logger ^0.1.0-dev.8

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.15
=> chore(mason): v0.1.0-dev.15

bricks/widget/__brick__/{{name.snakeCase()}}.dart, packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.22
=> chore(mason_cli): v0.1.0-dev.22

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.16
=> chore(mason): v0.1.0-dev.16

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.17
=> chore(mason): v0.1.0-dev.17

extensions/vscode/README.md, extensions/vscode/package.json, extensions/vscode/src/commands/add-brick.ts, extensions/vscode/src/commands/index.ts, extensions/vscode/src/commands/init.ts, extensions/vscode/src/commands/remove-brick.ts, extensions/vscode/src/extension.ts, extensions/vscode/src/mason/index.ts, extensions/vscode/src/mason/mason-add.ts, extensions/vscode/src/mason/mason-exec.ts, extensions/vscode/src/mason/mason-init.ts, extensions/vscode/src/mason/mason-remove.ts, extensions/vscode/src/utils/exec.ts
**READY**
- feat(vscode): support for init, add, and remove commands
=> feat(vscode): support for init, add, and remove commands

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/commands/add-brick.ts, extensions/vscode/src/commands/init.ts, extensions/vscode/src/commands/remove-brick.ts, extensions/vscode/src/mason/mason-remove.ts
**READY**
- chore(vscode): v0.1.1
=> chore(vscode): v0.1.1

bricks/random_color/hooks/pre_gen.dart, packages/mason/lib/src/hooks.dart
**READY**
- fix(mason): hook context.vars mutation
=> fix(mason): HookContext vars mutation

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.18
=> chore(mason): v0.1.0-dev.18

packages/mason/lib/src/mason_yaml.dart, packages/mason_cli/test/fixtures/add/widget/cat.dart, packages/mason_cli/test/fixtures/init/mason-lock.json, packages/mason_cli/test/fixtures/make/widget/my_widget.dart
**READY**
- refactor(mason): improve brick location serialization
=> refactor(mason): improve brick location serialization

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- refactor: improve brick location serialization for hosted bricks
```yaml
hello:
version: ^0.1.0
hello: ^0.1.0
```
=> chore(mason): v0.1.0-dev.19

packages/mason/lib/mason.dart
**READY**
- feat(mason): expose GeneratorTarget
=> feat(mason): expose GeneratorTarget

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.20
=> chore(mason): v0.1.0-dev.20

packages/mason/lib/mason.dart
READY
Exposing the `OverwriteRule`, this is required for any class that wants to extend the `GeneratorTarget` that got exposed in #349
=> fix(mason): expose `OverwriteRule` for `GeneratorTarget`

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.21
=> chore(mason): v0.1.0-dev.21

packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/remove_test.dart, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/README.md, packages/mason_cli/test/fixtures/new/hooks/README.md, packages/mason_cli/test/fixtures/new/simple/hello_world/README.md
**READY**
- fix(mason_cli): add link to mason badge in README
=> fix(mason_cli): add link to mason badge in README

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.24
=> chore(mason_cli): v0.1.0-dev.24

packages/mason_cli/README.md, packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/lib/src/commands/commands.dart, packages/mason_cli/lib/src/commands/upgrade.dart, packages/mason_cli/lib/src/install_brick.dart, packages/mason_cli/test/commands/upgrade_test.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
closes #310 
Installed bricks can be upgraded to their latest versions via the `upgrade` command.
```sh
mason upgrade
```
=> feat(mason_cli): upgrade command

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.25
=> chore(mason_cli): v0.1.0-dev.25

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/build.md, .github/ISSUE_TEMPLATE/ci.md, .github/ISSUE_TEMPLATE/refactor.md
READY
Fix some typos and make the format of the templates more coherent.
=> chore: make github issues more coherent

.github/workflows/mason.yaml, .github/workflows/mason_api.yaml, .github/workflows/mason_cli.yaml, .github/workflows/mason_logger.yaml, packages/mason/lib/src/render.dart, packages/mason/test/src/render_test.dart, packages/mason_cli/README.md
**READY**
- feat(mason): add mustacheCase lambda (closes #265)
```
{{name.mustacheCase()}} -> {{ Felix }}
```
=> feat(mason): add mustacheCase lambda

packages/mason_logger/CHANGELOG.md, packages/mason_logger/README.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.0-dev.9
=> chore(mason_logger): v0.1.0-dev.9

packages/mason/pubspec.yaml
**READY**
- chore(mason): upgrade mason_logger and mocktail
=> chore(mason): upgrade mason_logger and mocktail

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.23
=> chore(mason): v0.1.0-dev.23

.github/workflows/mason_cli.yaml, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): upgrade mason and mocktail
=> chore(mason_cli): upgrade mason and mocktail

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.26
=> chore(mason_cli): v0.1.0-dev.26

packages/mason/lib/src/render.dart, packages/mason/test/src/render_test.dart
**READY**
- fix(mason): render shorthand lambdas within loops
```
{{#items}}{{..lowerCase()}}
{{/items}}
```
```json
{
"items": ["A", "B", "C"]
}
```
```
a
b
c
```
```
{{#items}}{{name.lowerCase()}}
{{/items}}
```
```json
{
"items": [{ "name": "A" }, { "name": "B" }, { "name": "C" }]
}
```
```
a
b
c
```
=> fix(mason): render shorthand lambdas within loops

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.24
=> chore(mason): v0.1.0-dev.24

packages/mason_logger/example/main.dart, packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- feat(mason_logger): add chooseOne (part of #329) 
```dart
/// Prompts user with [message] to choose one value from the provided
/// [choices].
///
/// An optional [defaultValue] can be specified.
/// The [defaultValue] must be one of the provided [choices].
final favoriteColor = logger.chooseOne(
'What is your favorite color?',
choices: ['red', 'green', 'blue'],
defaultValue: 'blue',
);
```
=> feat(mason_logger): add chooseOne

packages/mason_logger/CHANGELOG.md, packages/mason_logger/README.md, packages/mason_logger/pubspec.yaml
**READY**
- feat: `chooseOne` API
```dart
final favoriteColor = logger.chooseOne(
'What is your favorite color?',
choices: ['red', 'green', 'blue'],
defaultValue: 'blue',
);
```
=> chore(mason_logger): v0.1.0-dev.10

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.5
=> chore(mason_api): v0.1.0-dev.5

.github/workflows/mason_cli.yaml, packages/mason_cli/CHANGELOG.md, packages/mason_cli/README.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.27
=> chore(mason_cli): v0.1.0-dev.27

bricks/favorite_color/__brick__/color.md, bricks/favorite_color/brick.yaml, packages/mason/lib/src/brick_yaml.dart, packages/mason/lib/src/brick_yaml.g.dart, packages/mason/test/src/brick_yaml_test.dart
**READY**
- feat(mason): brick.yaml vars support enum type (#324)
=> feat(mason): brick.yaml vars enum support

.github/workflows/mason_cli.yaml, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/bricks/enum_no_choices/brick.yaml, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/fixtures/make/favorite_color/color.md, packages/mason_cli/test/fixtures/make/mason.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- feat(mason_cli): support enum vars
=> feat(mason_cli): support enum vars

packages/mason/lib/src/generator.dart, packages/mason/test/src/generator_test.dart
**READY**
- fix(mason): do not prompt when overwrite rule is alwaysOverwrite
=> fix(mason): do not prompt when overwrite rule is alwaysOverwrite

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.25
=> chore(mason): v0.1.0-dev.25

.github/workflows/mason_cli.yaml, packages/mason_cli/CHANGELOG.md, packages/mason_cli/README.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.28
=> chore(mason_cli): v0.1.0-dev.28

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- fix: write errors and warnings to `stderr`
- `Logger().err(...)`
- `Logger().warn(...)`
- `Logger().progress(...).fail(...)`
=> chore(mason_logger): v0.1.0-dev.11

packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): upgrade to mocktail ^0.3.0
=> chore(mason_logger): upgrade to mocktail ^0.3.0

packages/mason_logger/README.md, packages/mason_logger/example/main.dart, packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- feat(mason_logger): chooseAny support (closes #329)
=> feat(mason_logger): chooseAny support

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- fix(mason_logger): choose api windows compatibility (closes #398 and closes #397)
=> fix(mason_logger): choose api windows compatibility

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.0-dev.12
- fix: `chooseOne` API windows compatibility
- feat: `chooseAny`
```dart
/// Ask user to choose zero or more options.
final desserts = logger.chooseAny(
'Which desserts do you like?',
choices: ['🍦', '🍪', '🍩'],
);
```
=> chore(mason_logger): v0.1.0-dev.12

packages/mason/lib/src/brick_yaml.dart, packages/mason/lib/src/brick_yaml.g.dart, packages/mason/pubspec.yaml, packages/mason/test/src/brick_yaml_test.dart
**READY**
- feat(mason): support array var type in brick.yaml
=> feat(mason): support array var type in brick.yaml

packages/mason/lib/src/generator.dart, packages/mason/test/bricks/loop/__brick__/main_{{#values}}{{{.}}}{{/values}}.txt, packages/mason/test/bricks/loop/brick.yaml, packages/mason/test/src/generator_test.dart
**READY**
- fix(mason): file path looping array resolution
=> fix(mason): file path looping array resolution

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- fix: file path looping array resolution
- feat: `brick.yaml` vars array support
```yaml
vars:
color:
type: array
description: Your desired build flavors
defaults:
- production
prompt: What build flavors would you like?
values:
- development
- staging
- production
```
=> chore(mason): v0.1.0-dev.26

packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/bricks/array_no_choices/brick.yaml, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/fixtures/make/flavors/README.md, packages/mason_cli/test/fixtures/make/flavors/main_development.dart, packages/mason_cli/test/fixtures/make/flavors/main_production.dart, packages/mason_cli/test/fixtures/make/mason.yaml
**READY**
- feat(mason_cli): support array vars
=> feat(mason_cli): support array vars

packages/mason_cli/README.md, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- feat(mason_cli): bump minimum mason version in new bricks
=> feat(mason_cli): bump minimum mason version in new bricks

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.29
- feat: support array vars in `brick.yaml`
- feat: bump minimum mason version in new bricks
=> chore(mason_cli): v0.1.0-dev.29

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
=> fix(mason_logger): correct J and K key mappings

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.0-dev.13
=> chore(mason_logger): v0.1.0-dev.13

packages/mason_cli/CHANGELOG.md, packages/mason_cli/README.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- feat: support bundling git and hosted bricks
```sh
mason bundle --source git https://github.com/:org/:repo
mason bundle --source hosted <BRICK_NAME>
```
=> chore(mason_cli): v0.1.0-dev.30

extensions/vscode/package.json, extensions/vscode/src/commands/make-brick.ts, extensions/vscode/src/extension.ts
**READY**
- feat(vscode): make global brick
=> feat(vscode): make global brick

extensions/vscode/src/commands/make-brick.ts, extensions/vscode/src/mason/mason-exec.ts, extensions/vscode/src/mason/mason-make.ts
**READY**
- feat(vscode): mason make support hooks
=> feat(vscode): mason make support hooks

extensions/vscode/CHANGELOG.md, extensions/vscode/README.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
- chore(vscode): v0.1.2
=> chore(vscode): v0.1.2

extensions/vscode/package.json
**READY**
- fix(vscode): add make commands to activationEvents
=> fix(vscode): add make commands to activationEvents

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
- chore(vscode): v0.1.3
=> chore(vscode): v0.1.3

extensions/vscode/src/commands/make-brick.ts
**READY**
- fix(vscode): make supports spaces in string vars
=> fix(vscode): make supports spaces in string vars

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
- chore(vscode): v0.1.4
=> chore(vscode): v0.1.4

.github/workflows/ci.yaml
**READY**
- ci: use semantic_pull_request workflow
=> ci: use semantic_pull_request workflow

packages/mason/lib/src/generator.dart
**READY**
- perf(mason): run substitutions in isolate and improve render specificity
=> perf(mason): run substitutions in isolate and improve render specificity

packages/mason_logger/example/main.dart, packages/mason_logger/lib/src/progress.dart, packages/mason_logger/test/src/mason_logger_test.dart, packages/mason_logger/test/src/progress_test.dart
**READY**
Closes #403 
Adds the `Progress.update` method to update the progress message and time elapsed.
=> feat(mason_logger): `Progress.update`

packages/mason_logger/CHANGELOG.md, packages/mason_logger/README.md, packages/mason_logger/example/main.dart, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.0-dev.14
=> chore(mason_logger): v0.1.0-dev.14

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.27
=> chore(mason): v0.1.0-dev.27

packages/mason/lib/src/exception.dart, packages/mason/test/src/exception_test.dart
**READY**
- fix(mason): override toString on MasonException
=> fix(mason): override toString on MasonException

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.28
=> chore(mason): v0.1.0-dev.28

packages/mason/pubspec.yaml, packages/mason/pubspec_overrides.yaml, packages/mason_cli/pubspec.yaml, packages/mason_cli/pubspec_overrides.yaml
**READY**
- chore: use pubspec_overrides.yaml
=> chore: use pubspec_overrides.yaml

bricks/random_color/hooks/pre_gen.dart, packages/mason/pubspec.yaml
**READY**
- refactor(mason): use mason_logger ^0.1.0
=> refactor(mason): use mason_logger ^0.1.0

packages/mason/lib/src/hooks.dart
**READY**
- perf(mason): speed up hooks execution by removing unnecessary file read
=> perf(mason): speed up hooks execution by removing unnecessary file read

packages/mason/lib/src/render.dart, packages/mason/test/src/render_test.dart
**READY**
Allows lambda shorthands to include whitespace and nested variables. Also refactors the `transpiled` extension to make it more readable.
Closes #433
=> fix: flexible lambda shorthand syntax

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.29
=> chore(mason): v0.1.0-dev.29

packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/lib/src/commands/init.dart, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/lib/src/commands/publish.dart, packages/mason_cli/lib/src/commands/search.dart, packages/mason_cli/lib/src/commands/unbundle.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/new_test.dart, packages/mason_cli/test/commands/publish_test.dart, packages/mason_cli/test/commands/search_test.dart, packages/mason_cli/test/commands/unbundle_test.dart
**READY**
- refactor(mason_cli): use mason: ^0.1.0-dev.29
=> refactor(mason_cli): use mason: ^0.1.0-dev.29

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.31
=> chore(mason_cli): v0.1.0-dev.31

packages/mason_logger/README.md
**READY**
- docs(mason_logger): fix typo in README snippet
=> docs(mason_logger): fix typo in README snippet

packages/mason_logger/lib/src/io.dart, packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/lib/src/progress.dart, packages/mason_logger/pubspec.yaml, packages/mason_logger/test/src/mason_logger_test.dart, packages/mason_logger/test/src/progress_test.dart, packages/mason_logger/test/src/stdio_overrides_test.dart
**READY**
- refactor(mason_logger): remove pkg:universal_io
=> refactor(mason_logger): remove pkg:universal_io

packages/mason/lib/src/bricks_json.dart, packages/mason/lib/src/bundler.dart, packages/mason/lib/src/generator.dart, packages/mason/lib/src/git.dart, packages/mason/lib/src/mason_yaml.dart, packages/mason/pubspec.yaml, packages/mason/test/src/bricks_json_test.dart, packages/mason/test/src/bundler_test.dart, packages/mason/test/src/generator_test.dart, packages/mason/test/src/git_test.dart, packages/mason/test/src/mason_yaml_test.dart
**READY**
- refactor(mason): remove pkg:universal_io
=> refactor(mason): remove pkg:universal_io

packages/mason_api/lib/src/mason_api.dart, packages/mason_api/pubspec.yaml, packages/mason_api/test/src/mason_api_test.dart
**READY**
- refactor(mason_api): remove pkg:universal_io
=> refactor(mason_api): remove pkg:universal_io

packages/mason_cli/bin/mason.dart, packages/mason_cli/lib/src/command.dart, packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/lib/src/commands/publish.dart, packages/mason_cli/lib/src/commands/unbundle.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/add_test.dart, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/cache_test.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/init_test.dart, packages/mason_cli/test/commands/list_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/commands/new_test.dart, packages/mason_cli/test/commands/publish_test.dart, packages/mason_cli/test/commands/remove_test.dart, packages/mason_cli/test/commands/unbundle_test.dart, packages/mason_cli/test/commands/update_test.dart, packages/mason_cli/test/commands/upgrade_test.dart, packages/mason_cli/test/helpers/directories_deep_equal.dart, packages/mason_cli/test/helpers/set_up_testing_environment.dart, packages/mason_cli/test/mason_generator_test.dart, packages/mason_cli/test/src/command_test.dart
**READY**
- refactor(mason_cli): remove pkg:universal_io
=> refactor(mason_cli): remove pkg:universal_io

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/lib/src/progress.dart
**READY**
- refactor(mason_logger): internal consistency and renaming
=> refactor(mason_logger): internal consistency and renaming

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.1
=> chore(mason_logger): v0.1.1

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.6
=> chore(mason_api): v0.1.0-dev.6

packages/mason/CHANGELOG.md, packages/mason/README.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.30
=> chore(mason): v0.1.0-dev.30

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.32
=> chore(mason_cli): v0.1.0-dev.32

packages/mason/lib/src/render.dart, packages/mason/test/src/render_test.dart
**READY**
- fix(mason): render asymmetrical shorthand lambda expressions correctly
=> fix(mason): render asymmetrical shorthand lambda expressions correctly

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.31
=> chore(mason): v0.1.0-dev.31

packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/test/bundles/greeting_bundle.dart, packages/mason_cli/test/bundles/hooks_bundle.dart, packages/mason_cli/test/bundles/legacy_greeting_bundle.dart, packages/mason_cli/test/commands/bundle_test.dart
**READY**
- feat(mason_cli): disable lints in dart bundles
=> feat(mason_cli): disable lints in dart bundles

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.33
=> chore(mason_cli): v0.1.0-dev.33

.github/workflows/mason_cli.yaml, packages/mason_api/example/main.dart, packages/mason_api/lib/src/mason_api.dart, packages/mason_api/test/src/mason_api_test.dart, packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/test/src/command_runner_test.dart
Hello @felangel 
Your http client api implementation looks very clean. Would love to take a look at the backend side. However I saw that the client is not closed as suggested in the [http documentation](https://pub.dev/documentation/http/latest/http/Client/close.html). Some tests were failing but by the looks of it is is because of some not found files. Maybe you can give it a try on your system.
All the best 
Julian
**HOLD**
I thought let's just give ``MasonApi`` a public ``close`` method that can be called in the ``finally`` blocks of where you perform the requests.
=> feat(mason_api): add close

packages/mason_api/pubspec.yaml, packages/mason_api/test/src/mason_api_test.dart
**READY**
- chore(mason_api): upgrade to mocktail ^0.3.0
=> chore(mason_api): upgrade to mocktail ^0.3.0

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.7
=> chore(mason_api): v0.1.0-dev.7

.github/workflows/mason_cli.yaml, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): upgrade to mason_api ^0.1.0-dev.7
=> chore(mason_cli): upgrade to mason_api ^0.1.0-dev.7

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.34
=> chore(mason_cli): v0.1.0-dev.34

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
- chore(vscode): v0.1.5
=> chore(vscode): v0.1.5

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.2
=> chore(mason_logger): v0.1.2

.github/workflows/mason.yaml, .github/workflows/mason_api.yaml, .github/workflows/mason_cli.yaml, .github/workflows/mason_logger.yaml, packages/mason/lib/src/compute.dart
**READY**
- ci: remove deprecated .packages
=> ci: remove deprecated .packages

packages/mason/CHANGELOG.md, packages/mason/README.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.32
=> chore(mason): v0.1.0-dev.32

packages/mason_cli/lib/src/install_brick.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/upgrade_test.dart
**READY**
- fix(mason_cli): upgrade from subdirectory w/relative paths (closes #515)
=> fix(mason_cli): upgrade from subdirectory w/relative paths

packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/test/commands/add_test.dart
**READY**
- fix(mason_cli): add from subdirectory w/relative path (related to #515)
=> fix(mason_cli): add from subdirectory w/relative path

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.33
=> chore(mason): v0.1.0-dev.33

packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/lib/src/commands/publish.dart, packages/mason_cli/lib/src/commands/search.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/publish_test.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- feat(mason_cli): use logger link api
=> feat(mason_cli): use logger link api

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.35
=> chore(mason_cli): v0.1.0-dev.35

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.8
=> chore(mason_api): v0.1.0-dev.8

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.36
=> chore(mason_cli): v0.1.0-dev.36

packages/mason/CHANGELOG.md, packages/mason/LICENSE, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.34
=> chore(mason): v0.1.0-dev.34

packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): upgrade deps
=> chore(mason_cli): upgrade deps

packages/mason_cli/CHANGELOG.md, packages/mason_cli/LICENSE, packages/mason_cli/README.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.37
=> chore(mason_cli): v0.1.0-dev.37

bricks/hooks/hooks/post_gen.dart, bricks/hooks/hooks/pre_gen.dart, packages/mason/lib/src/hooks.dart, packages/mason/test/bundles/hooks_bundle.dart, packages/mason/test/src/bundler_test.dart, packages/mason/test/src/generator_test.dart, packages/mason_cli/test/bundles/hooks_bundle.dart, packages/mason_cli/test/commands/bundle_test.dart
**READY**
- feat(mason)!: avoid templating hook contents (closes #514)
=> perf(mason)!: avoid templating hook contents

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.2
=> chore(mason_logger): v0.2.2

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml
**READY**
- chore(mason): v0.1.0-dev.35
=> chore(mason): v0.1.0-dev.35

extensions/vscode/CHANGELOG.md, extensions/vscode/README.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/schema/brick.yaml.schema.json
**READY**
- chore(vscode): v0.1.6
=> chore(vscode): v0.1.6

packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- feat(mason_cli): upgrade to mason 0.1.0-dev.35
=> feat(mason_cli): upgrade to mason 0.1.0-dev.35

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.38
=> chore(mason_cli): v0.1.0-dev.38

packages/mason/lib/src/bundler.dart
**READY**
- fix(mason): support mp3 binary file types
=> fix(mason): support mp3 binary file types

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.36
=> chore(mason): v0.1.0-dev.36

packages/mason_cli/test/fixtures/new/hooks/brick.yaml
**READY**
- test(mason_cli): fix failing test in new_test.dart
=> test(mason_cli): fix failing test in new_test.dart

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.37
=> chore(mason): v0.1.0-dev.37

.github/workflows/mason_cli.yaml, packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.39
=> chore(mason_cli): v0.1.0-dev.39

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.3
=> chore(mason_logger): v0.2.3

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.39
=> chore(mason): v0.1.0-dev.39

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.40
=> chore(mason_cli): v0.1.0-dev.40

extensions/vscode/schema/mason.yaml.schema.json
**READY**
In `mason.yaml.schema.json` the pattern for brick url has been changed to `^(https?|ssh)://` to accept ssh scheme in VSCode extension.
=> fix(vscode): git url schema validation

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
- chore(vscode): v0.1.7
=> chore(vscode): v0.1.7

packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- feat(mason_cli): add completion
=> feat(mason_cli): add completion

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.41
=> chore(mason_cli): v0.1.0-dev.41

packages/mason_cli/lib/src/install_brick.dart, packages/mason_cli/test/commands/add_test.dart
**READY**
- feat(mason_cli): improve error when running add in an uninitialized directory (closes #633)
=> feat(mason_cli): improve error when running add in an uninitialized directory

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.40
=> chore(mason): v0.1.0-dev.40

.github/workflows/mason_cli.yaml, packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.42
=> chore(mason_cli): v0.1.0-dev.42

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- fix(mason_logger): warn without a tag should not include `[]` (closes #715)
=> fix(mason_logger): warn without a tag should not include `[]`

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.4
=> chore(mason_logger): v0.2.4

packages/mason_api/CHANGELOG.md, packages/mason_api/lib/src/mason_api.dart, packages/mason_api/pubspec.yaml, packages/mason_api/test/src/mason_api_test.dart
**READY**
- chore(mason_api): v0.1.0-dev.9
=> chore(mason_api): v0.1.0-dev.9

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.41
=> chore(mason): v0.1.0-dev.41

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.43
=> chore(mason_cli): v0.1.0-dev.43

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.44
=> chore(mason_cli): v0.1.0-dev.44

extensions/vscode/src/mason/mason-make.ts
**READY**
- fix(vscode): support spaces in mason make `--output-dir` (closes #714)
=> fix(vscode): support spaces in mason make `--output-dir`

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
- chore(vscode): v0.1.8
=> chore(vscode): v0.1.8

packages/mason/analysis_options.yaml, packages/mason/lib/mason.dart, packages/mason/lib/src/brick.dart, packages/mason/lib/src/brick_yaml.dart, packages/mason/pubspec.yaml, packages/mason_api/analysis_options.yaml, packages/mason_api/lib/mason_api.dart, packages/mason_api/pubspec.yaml, packages/mason_cli/analysis_options.yaml, packages/mason_cli/lib/mason_cli.dart, packages/mason_cli/lib/src/commands/search.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/ensure_build_test.dart, packages/mason_logger/analysis_options.yaml, packages/mason_logger/lib/mason_logger.dart, packages/mason_logger/pubspec.yaml
**READY**
- chore(deps): upgrade to very_good_analysis ^4.0.0
=> chore(deps): upgrade to very_good_analysis ^4.0.0

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.10
=> chore(mason_api): v0.1.0-dev.10

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.5
=> chore(mason_logger): v0.2.5

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.42
=> chore(mason): v0.1.0-dev.42

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.45
=> chore(mason_cli): v0.1.0-dev.45

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.43
=> chore(mason): v0.1.0-dev.43

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.46
=> chore(mason_cli): v0.1.0-dev.46

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
- chore(vscode): v0.1.9
=> chore(vscode): v0.1.9

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.44
=> chore(mason): v0.1.0-dev.44

.github/workflows/mason_cli.yaml, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/README.md, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/README.md, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/README.md, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- feat(mason_cli): add repository field and README updates to new brick
=> feat(mason_cli): add repository field and README updates to new brick

packages/mason/lib/src/bundler.dart, packages/mason/lib/src/mason_bundle.dart, packages/mason/lib/src/mason_bundle.g.dart, packages/mason/test/bricks/custom_registry/brick.yaml, packages/mason/test/bricks/no_registry/brick.yaml, packages/mason/test/src/bundler_test.dart, packages/mason/test/src/mason_bundle_test.dart
**READY**
- feat(mason): add publishTo to MasonBundle
=> feat(mason): add `publishTo` to `MasonBundle`

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.45
=> chore(mason): v0.1.0-dev.45

packages/mason/CHANGELOG.md, packages/mason/lib/src/mason_bundle.dart, packages/mason/lib/src/mason_bundle.g.dart, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.46
=> chore(mason): v0.1.0-dev.46

packages/mason_cli/CHANGELOG.md, packages/mason_cli/README.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.47
=> chore(mason_cli): v0.1.0-dev.47

extensions/vscode/README.md, extensions/vscode/package.json, extensions/vscode/src/commands/index.ts, extensions/vscode/src/commands/make-brick.ts, extensions/vscode/src/commands/new-brick.ts, extensions/vscode/src/extension.ts, extensions/vscode/src/mason/index.ts, extensions/vscode/src/mason/mason-new.ts, extensions/vscode/src/utils/index.ts, extensions/vscode/src/utils/prompt-for-target-directory.ts
**READY**
- feat(vscode): support mason new brick
=> feat(vscode): support mason new brick

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json
**READY**
- chore(vscode): v0.1.10
=> chore(vscode): v0.1.10

packages/mason_cli/lib/src/commands/publish.dart, packages/mason_cli/test/commands/publish_test.dart
**READY**
- feat(mason_cli): add `--force` flag to `publish` command
- feat(mason_cli): add `--dry-run` flag to `publish` command (closes #355)
=> feat(mason_cli): add `--force` and `--dry-run` to `publish` command

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.48
=> chore(mason_cli): v0.1.0-dev.48

packages/mason_cli/lib/src/commands/add.dart
**READY**
- refactor(mason_cli): mason add uses build instead of compile
=> refactor(mason_cli): mason add uses build instead of compile

.github/workflows/ci.yaml, .github/workflows/mason.yaml, .github/workflows/mason_api.yaml, .github/workflows/mason_cli.yaml, .github/workflows/mason_logger.yaml, .github/workflows/vscode.yaml
**READY**
- ci: concurrency cancel in progress jobs
=> ci: concurrency cancel in progress jobs

packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/test/commands/bundle_test.dart
**READY**
- refactor(mason_cli): streamline stdout from mason bundle
=> refactor(mason_cli): streamline stdout from mason bundle

packages/mason/test/src/generator_test.dart, packages/mason_cli/test/commands/add_test.dart, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/cache_test.dart, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/init_test.dart, packages/mason_cli/test/commands/list_test.dart, packages/mason_cli/test/commands/login_test.dart, packages/mason_cli/test/commands/logout_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/commands/new_test.dart, packages/mason_cli/test/commands/publish_test.dart, packages/mason_cli/test/commands/remove_test.dart, packages/mason_cli/test/commands/search_test.dart, packages/mason_cli/test/commands/unbundle_test.dart, packages/mason_cli/test/commands/update_test.dart, packages/mason_cli/test/commands/upgrade_test.dart, packages/mason_cli/test/mason_generator_test.dart, packages/mason_cli/test/src/command_runner_test.dart, packages/mason_cli/test/src/command_test.dart, packages/mason_logger/test/src/mason_logger_test.dart, packages/mason_logger/test/src/progress_test.dart
**READY**
- refactor: use private mocks
=> refactor: use private mocks

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason/test/bricks/nested_conditional/brick.yaml, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.47
=> chore(mason): v0.1.0-dev.47

packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/commands/new_test.dart
**READY**
- feat(mason_cli): mason new updates existing brick (closes #789)
=> feat(mason_cli): mason new updates existing brick

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.49
=> chore(mason_cli): v0.1.0-dev.49

packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/lib/src/install_brick.dart
**READY**
- feat(mason_cli): simplify `mason add` stdout
=> feat(mason_cli): simplify `mason add` stdout

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.50
=> chore(mason_cli): v0.1.0-dev.50

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.48
=> chore(mason): v0.1.0-dev.48

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.49
=> chore(mason): v0.1.0-dev.49

packages/mason_api/lib/src/mason_api.dart, packages/mason_api/test/src/mason_api_test.dart
**READY**
- chore(mason_api): remove redundant parameter
=> chore(mason_api): remove redundant parameter

packages/mason_logger/CHANGELOG.md, packages/mason_logger/README.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.6
=> chore(mason_logger): v0.2.6

packages/mason_logger/analysis_options.yaml, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): upgrade to very_good_analysis 5.0.0
=> chore(mason_logger): upgrade to very_good_analysis 5.0.0

packages/mason/pubspec.yaml, packages/mason_api/pubspec.yaml
**READY**
- chore: allow latest `pkg:http`
=> chore: allow latest `pkg:http`

packages/mason_logger/CHANGELOG.md, packages/mason_logger/LICENSE, packages/mason_logger/README.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.7
=> chore(mason_logger): v0.2.7

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.50
=> chore(mason): v0.1.0-dev.50

.github/workflows/mason_cli.yaml, packages/mason_cli/CHANGELOG.md, packages/mason_cli/LICENSE, packages/mason_cli/README.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.51
=> chore(mason_cli): v0.1.0-dev.51

extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/commands/add-brick.ts, extensions/vscode/src/commands/init.ts, extensions/vscode/src/commands/make-brick.ts, extensions/vscode/src/commands/remove-brick.ts, extensions/vscode/src/extension.ts, extensions/vscode/src/mason/mason-add.ts, extensions/vscode/src/mason/mason-exec.ts, extensions/vscode/src/mason/mason-get.ts, extensions/vscode/src/mason/mason-init.ts, extensions/vscode/src/mason/mason-make.ts, extensions/vscode/src/mason/mason-new.ts, extensions/vscode/src/mason/mason-remove.ts
**READY**
- chore(deps-dev): bump prettier from 2.8.8 to 3.0.0 in extensions/vscode
=> chore(deps-dev): bump prettier from 2.8.8 to 3.0.0 in extensions/vscode

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.8
=> chore(mason_logger): v0.2.8

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.9
=> chore(mason_logger): v0.2.9

packages/mason/pubspec.yaml, packages/mason/test/src/hooks_test.dart
**READY**
- chore(mason): upgrade to mason_logger ^0.2.9
=> chore(mason): upgrade to mason_logger ^0.2.9

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason/test/src/bricks_json_test.dart, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.51
=> chore(mason): v0.1.0-dev.51

packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/bundle_test.dart
**READY**
- chore(mason_cli): upgrade to mason ^0.1.0-dev.51
=> chore(mason_cli): upgrade to mason ^0.1.0-dev.51

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.52
=> chore(mason_cli): v0.1.0-dev.52

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.10
=> chore(mason_logger): v0.2.10

packages/mason/lib/src/generator.dart
**READY**
Adds documentation to reference the DirectoryGeneratorTarget.
I found this to be useful when looking at the signature of `generator.generate()`.
=> docs(mason): include reference to DirectoryGeneratorTarget

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.53
=> chore(mason_cli): v0.1.0-dev.53

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.11
=> chore(mason_logger): v0.2.11

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0-dev.11
=> chore(mason_api): v0.1.0-dev.11

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.52
=> chore(mason): v0.1.0-dev.52

.github/dependabot.yaml
**READY**
- ci: dependabot groups
=> ci: dependabot groups

extensions/vscode/CHANGELOG.md, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/commands/add-brick.ts, extensions/vscode/src/commands/init.ts, extensions/vscode/src/commands/make-brick.ts, extensions/vscode/src/commands/new-brick.ts, extensions/vscode/src/commands/remove-brick.ts, extensions/vscode/src/mason/mason-remove.ts, extensions/vscode/src/utils/prompt-for-target-directory.ts
**READY**
- chore(vscode): v0.1.12
=> chore(vscode): v0.1.12

packages/mason_logger/CHANGELOG.md, packages/mason_logger/LICENSE, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.13
=> chore(mason_logger): v0.2.13

packages/mason_logger/lib/src/ffi/windows_terminal.dart, packages/mason_logger/pubspec.yaml
**READY**
- fix(mason_logger): revert "remove deprecated methods in `WindowsTerminal`"
=> fix(mason_logger): revert "remove deprecated methods in `WindowsTerminal`"

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.15
=> chore(mason_logger): v0.2.15

.github/workflows/mason_cli.yaml, packages/mason/pubspec.yaml
**READY**
- chore(mason): upgrade `pkg:mason_logger`
- bump minimum Dart SDK version to 3.3.0
=> chore(mason): upgrade `pkg:mason_logger`

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/lib/src/commands/unbundle.dart, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/update_test.dart
**READY**
- chore(mason_cli): v0.1.0-dev.55
=> chore(mason_cli): v0.1.0-dev.55

packages/mason/lib/src/generator.dart, packages/mason/lib/src/hooks.dart, packages/mason/test/fixtures/programmatic_usage/main.dart, packages/mason/test/src/hooks_test.dart
**READY**
- fix(mason): compile hooks to AOT when using AOT runtime (closes #1329)
=> fix(mason): compile hooks to AOT when using AOT runtime

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.54
=> chore(mason): v0.1.0-dev.54

packages/mason/lib/src/generator.dart, packages/mason/lib/src/hooks.dart
**READY**
- fix(mason): nested hooks execution
=> fix(mason): nested hooks execution

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.55
=> chore(mason): v0.1.0-dev.55

packages/mason/CHANGELOG.md, packages/mason/lib/src/generator.dart, packages/mason/lib/src/hooks.dart, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason/test/src/hooks_test.dart, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.56
=> chore(mason): v0.1.0-dev.56

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.57
=> chore(mason): v0.1.0-dev.57

packages/mason_cli/README.md
**READY**
Today I forgot that I raised https://github.com/felangel/mason/issues/378, when looking at the documentation there was no reminder/information about it, and I think it is worth mentioning it within the documentation.
=> docs: document non top level partials 

packages/mason/pubspec.yaml, packages/mason_api/pubspec.yaml, packages/mason_cli/pubspec.yaml, packages/mason_logger/pubspec.yaml
**READY**
- chore: add `funding` to `pubspec.yaml`
=> chore: add `funding` to `pubspec.yaml`

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.16
=> chore(mason_logger): v0.2.16

packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): tighten deps
=> chore(mason_logger): tighten deps

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.3.0
=> chore(mason_logger): v0.3.0

packages/mason_api/lib/src/models/brick_search_result.g.dart, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): tighten deps
=> chore(mason_api): tighten deps

packages/mason/pubspec.yaml
**READY**
- chore(mason): tighten deps
=> chore(mason): tighten deps

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.58
=> chore(mason): v0.1.0-dev.58

packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): tighten deps
=> chore(mason_cli): tighten deps

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.56
=> chore(mason_cli): v0.1.0-dev.56

packages/mason/pubspec.yaml
**READY**
- chore(mason): loosen `pkg:collection` constraint for Flutter compatibility
=> chore(mason): loosen `pkg:collection` constraint for Flutter compatibility

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.59
=> chore(mason): v0.1.0-dev.59

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.3.1
=> chore(mason_logger): v0.3.1

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.60
=> chore(mason): v0.1.0-dev.60

packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/test/commands/add_test.dart
**READY**
- feat(mason_cli): `mason add` brick conflicts (closes #1310)
=> feat(mason_cli): `mason add` brick conflicts

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.57
=> chore(mason_cli): v0.1.0-dev.57

packages/mason_api/CHANGELOG.md, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.0 (closes #1432)
=> chore(mason_api): v0.1.0

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/commands/make_test.dart
**READY**
- chore(mason_cli): v0.1.0 (closes #1432)
=> chore(mason_cli): v0.1.0

packages/mason_cli/README.md, packages/mason_cli/README.zh.md, packages/mason_cli/lib/src/commands/init.dart, packages/mason_cli/test/fixtures/init/mason.yaml
**READY**
- fix(mason_cli): adjust generate `mason.yaml` from `mason init`
=> fix(mason_cli): adjust generate `mason.yaml` from `mason init`

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.1
=> chore(mason_cli): v0.1.1

packages/mason_cli/lib/src/command_runner.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- feat(mason_cli): improve `mason --version` output (closes #1478)
Sample Output
```sh
$ mason --version
mason_cli 0.1.1 • command-line interface
mason 0.1.0 • core templating engine
```
=> feat(mason_cli): improve `mason --version` output

packages/mason_cli/CHANGELOG.md, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.2
=> chore(mason_cli): v0.1.2

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.3.2
=> chore(mason_logger): v0.3.2

bricks/hello/brick.yaml, packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/analysis_options.yaml, packages/mason_cli/test/bricks/array_no_choices/brick.yaml, packages/mason_cli/test/bricks/enum_no_choices/brick.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.1
=> chore(mason): v0.1.1

packages/mason_logger/lib/src/ffi/windows_terminal.dart, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): upgrade to `pkg:win32 ^5.11.0`
=> chore(mason_logger): upgrade to `pkg:win32 ^5.11.0`

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.3.3
=> chore(mason_logger): v0.3.3

packages/mason_api/CHANGELOG.md, packages/mason_api/lib/src/models/credentials.dart, packages/mason_api/pubspec.yaml
**READY**
- chore(mason_api): v0.1.1
=> chore(mason_api): v0.1.1
