CHANGELOG.md, lib/mason.dart, lib/src/commands/get.dart, lib/src/generator.dart, lib/src/mason_cache.dart, lib/src/version.dart, pubspec.yaml
- feat: export `MasonGenerator` and relevant objects to allow `mason` to be consumed as a library
- feat: expose `fromGitPath` on `MasonGenerator`
=> feat: MasonGenerator.fromGitPath

.github/workflows/main.yaml, README.md, lib/src/bundler.dart, lib/src/commands/get.dart, lib/src/commands/new.dart, lib/src/generator.dart, lib/src/mason_cache.dart, test/commands/bundle_test.dart, test/commands/get_test.dart, test/helpers/directories_deep_equal.dart
Normalize path according to platform in order to avoid escaping issues (felangel#39)
- fix: normalize brick location path according to platform and use posix-styled path for brick registering relative path to avoid escaping-related errors (closes #39)
On Windows, posix separator usage leads to issues.
=> fix: normalize brick paths to avoid escaping issues (felangel#39)

README.md
- docs: add bundling documentation to README (closes #38)
=> docs: add bundling documentation to README

lib/src/command.dart, lib/src/commands/get.dart, lib/src/commands/make.dart, lib/src/commands/new.dart, lib/src/mason_cache.dart, test/commands/make_test.dart, test/commands/new_test.dart
- fix: improved error handling and error reporting
- improve error message when `mason new` is missing a brick name (closes #37)
- improve error message when `mason make` is missing a subcommand
- `mason get` handle empty brick list in `mason.yaml`
- avoid hydrating cache when `bricks.json` is empty.
=> fix: improved error handling and error reporting

.gitignore, lib/src/command.dart, lib/src/commands/get.dart, lib/src/commands/new.dart, test/commands/new_test.dart, test/helpers/directories_deep_equal.dart
`mason new <template>` automatically installs the template so that it can be used via `mason make <template>` immediately without requiring a `mason get`.
=> feat: new templates are readily available

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- feat: new templates are readily available
- docs: update README usage section to include `bundle`
- docs: update file resolution section and include note about unescaped variables
=> chore: v0.0.1-dev.31

README.md
Mustache changed the `.com` link to `.io` for the mustache5 manual. Just updated the link. 👍
=> docs: update mustache manual link

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- feat: mason install command for global brick templates
- docs: update mustache manual link
- docs: update mason.yaml from init to use https for git
=> chore: v0.0.1-dev.33

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- fix: local mason get installation location for remote bricks
- fix!: always attempt to fetch latest remote brick
- `mason get` no longer supports `--force` since it is handled automatically
=> chore: v0.0.1-dev.34

lib/src/mason_cache.dart, test/commands/cache_test.dart
When running `mason cache clear --force` I expect the cache to be removed but not the current directory/files.
=> fix: mason cache clear --force target

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- fix: adjust `mason cache clear --force` target directory to avoid deleting local files
=> chore: v0.0.1-dev.35

CHANGELOG.md, lib/mason.dart, lib/src/brick_yaml.dart, lib/src/bricks_json.dart, lib/src/command.dart, lib/src/commands/cache.dart, lib/src/commands/get.dart, lib/src/commands/install.dart, lib/src/commands/new.dart, lib/src/commands/uninstall.dart, lib/src/generator.dart, lib/src/mason_yaml.dart, lib/src/version.dart, pubspec.yaml, test/commands/cache_test.dart, test/commands/get_test.dart, test/commands/list_test.dart, test/commands/new_test.dart, test/commands/uninstall_test.dart
- feat!: remove `--force` from `mason cache clear`
- `mason cache clear` will remove all local bricks so `--force` is not necessary
- fix: `mason cache clear` behavior to always clear local and global brick caches
- fix: local and global brick installation conflicts
- fix: `mason list` duplicate bricks
- refactor: `MasonCache` to `BricksJson`
- simplification of internal APIs and cache implementation
=> feat!: v0.0.1-dev.38

README.md, lib/src/commands/bundle.dart
In order to align with other CLI conventions the output directory location option was renamed in the `mason bundle` command.
```sh
$ mason bundle ./path/to/brick --directory ./path/to/output/directory
$ mason bundle ./path/to/brick -d ./path/to/output/directory
```
```sh
$ mason bundle ./path/to/brick --output-dir ./path/to/output/directory
$ mason bundle ./path/to/brick -o ./path/to/output/directory
```
=> feat!: update mason bundle output directory option

README.md, example/README.md, lib/src/commands/make.dart, test/commands/make_test.dart, test/fixtures/make/output_dir/dir/GREETINGS.md
- refactor!: `mason make --json` (`-j`) renamed to `--config-path` (`-c`)
- feat: `mason make` additional option `--output-dir` (`-o`) to specify a custom output directory (closes #76)
Any variables can be passed via a config file:
```dart
$ mason make hello -c config.json
```
where `config.json` is:
```json
{
"name": "Felix"
}
```
By default `mason make` will generate the template in the current working directory but a custom output directory can be specified via the `-o` option:
```sh
$ mason make hello --name Felix -o ./path/to/directory
```
=> feat!: update mason make command to support a custom output directory

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- refactor!: rename `mason make --json` (`-j`) to `mason make --config-path` (`-c`)
- refactor!: rename `mason bundle --directory` (`-d`) to `mason bundle --output-dir` (`-o`)
- feat!: update `mason make` to support custom output directory via `--output-dir` (`-o`)
=> chore: v0.0.1-dev.39

lib/src/generator.dart, test/commands/make_test.dart
`mason make <BRICK_NAME> -o ./path/to/custom/directory` will create the target directory recursively if it doesn't already exist
=> fix: create target directory if not existent

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- fix: improve `mason make --help` to show complete usage information
```sh
Generate code using an existing brick template.
Usage: mason make [arguments]
-h, --help           Print this usage information.
-c, --config-path    Path to config json file containing variables.
-o, --output-dir     Directory where to output the generated code.
(defaults to ".")
Run "mason help" to see global options.
```
=> chore: v0.0.1-dev.42

CHANGELOG.md, lib/src/version.dart, pubspec.yaml
- fix: `mason bundle` add `.otf` support.
=> chore: v0.0.1-dev.45

packages/mason_cli/README.md, packages/mason_cli/lib/src/command.dart, packages/mason_cli/lib/src/commands/list.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/list_test.dart, packages/mason_cli/test/src/command_runner_test.dart
**READY**
- feat(mason_cli): add mason list --global (closes #159)
```sh
mason list
mason list --global
mason ls
mason ls -g
```
=> feat(mason_cli): add mason list --global

bricks/bio/__brick__/ABOUT.md, bricks/bio/brick.yaml, packages/mason/lib/mason.dart, packages/mason/lib/src/brick_yaml.dart, packages/mason/lib/src/brick_yaml.g.dart, packages/mason/lib/src/generator.dart, packages/mason/lib/src/mason_bundle.dart, packages/mason/lib/src/mason_bundle.g.dart, packages/mason/pubspec.yaml, packages/mason/test/src/brick_yaml_test.dart, packages/mason/test/src/generator_test.dart, packages/mason/test/src/mason_bundle_test.dart, packages/mason_cli/example/mason.yaml, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/pubspec.yaml, packages/mason_cli/test/commands/bundle_test.dart, packages/mason_cli/test/commands/make_test.dart, packages/mason_cli/test/fixtures/make/bio/ABOUT.md, packages/mason_cli/test/fixtures/make/mason.yaml, packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
Currently, it's not possible to provide defaults or metadata about the variables that a brick requires:
```yaml
name: bio
description: A Bio Template
version: '1.0.0'
vars:
- name
- age
- isDeveloper
```
This pull request updates the core mason library to allow developers to specify the type, description, default value, and prompt for each variable.
```yaml
name: bio
description: A Bio Template
version: 1.0.0
vars:
name:
type: string
description: Name of the current user
default: Dash
prompt: What is your name?
age:
type: number
description: Age of the current user
default: 42
prompt: How old are you?
isDeveloper:
type: boolean
description: If the current user is a developer
default: false
prompt: Are you a developer?
```
The changes are backward compatible so previous …
=> feat: brick advanced variable support

packages/mason/lib/src/bundler.dart, packages/mason/lib/src/generator.dart, packages/mason/lib/src/mason_bundle.dart, packages/mason/lib/src/mason_bundle.g.dart, packages/mason/test/src/generator_test.dart, packages/mason/test/src/mason_bundle_test.dart, packages/mason_cli/lib/src/commands/init.dart, packages/mason_cli/lib/src/commands/make.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/mason_generator_test.dart
**READY**
- `package:mason` Core API Updates
- `MasonBundle`
- Use named constructor parameters instead of positional parameters
- `MasonGenerator.generate(...)`
- Accepts optional `Logger` and `FileConflictResolution`
- `DirectoryGeneratorTarget`
- No longer accepts optional `Logger` and `FileConflictResolution` (moved to `generate` API above)
**Before**
```dart
final generator = MasonGenerator.fromBundle(myBundle);
final target = DirectoryGeneratorTarget(dir, Logger(), FileConflictResolution.skip);
await generator.generate(target, vars: {...});
```
**After**
```dart
final generator = MasonGenerator.fromBundle(myBundle);
final target = DirectoryGeneratorTarget(dir);
await generator.generate(
DirectoryGeneratorTarget(tempDir),
vars: {...},
logger: Logger(), // optional logger …
```
=> refactor(mason)!: API updates to MasonBundle, MasonGenerator, and DirectoryGeneratorTarget

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
Ready
Both `prompt` and `confirm` do not support multi-line messages, when we write the message after getting the result we dont move the cursor up the amount of lines in the message.
=> fix(mason_logger): multiline prompts are outputting twice

packages/mason/lib/src/render.dart, packages/mason/test/src/render_test.dart
**READY**
Don't allow `{{` in between `{{}}` or `{{{}}}` in the regex when matching for shorthand so that other variables are not accidentally caught in the middle. 
Currently:
Renderer will match everything in between the very first `{{` and the very last `}}` in `{{#is_prefixed}}Greeting: {{/is_prefixed}}{{greeting.upperCase()}}!` when looking for shorthands, so it will replace `#is_prefixed}}Greeting: {{/is_prefixed}}{{greeting.upperCase()`. 
With these changes: 
Renderer will only match and replace `{{greeting.upperCase()}}`
=> Fix: Allow regular mustache syntax before shorthand syntax in string

bricks/widget/__brick__/{{name.snakeCase()}}.dart
**READY/IN DEVELOPMENT/HOLD**
I started to explore bricks and noticed that the configuration of widget brick is off. This could go the other way too - to remove the `child` in `Container`, but I guess it's better to put more code in this brick, rather than less. I also made `key` nullable as I suppose this should be null-safe.
=> feat(widget): simplify widget brick to use SizedBox

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/lib/src/progress.dart, packages/mason_logger/test/src/mason_logger_test.dart, packages/mason_logger/test/src/progress_test.dart
Fixes #362: `Progress.fail` & `err` should write to `stderr`
**READY**/IN DEVELOPMENT/HOLD
Updates `mason_logger` to use `stderr` where relevant:
- `Progess.fail`
- `Logger.err`
=> fix(mason_logger): err should write to `stderr`

packages/mason_cli/README.md
READY
Update the broken link for `app icon example brick` in `mason_cli`'s `README.md`
=> docs(mason_cli): fix app_icon link in README

extensions/vscode/src/commands/make-brick.ts
**READY**
Right now, if there's an enum variable declaration in your `brick.yaml` but there's no default value specified, VSCode extension `make*Command` execution breaks without producing any output. If there's no default, the extension should pick up first value from `values` as the default, similarly to what the CLI does in this situation.
=> fix(vscode): assume enum default prompt value

packages/mason_logger/lib/src/progress.dart, packages/mason_logger/test/src/progress_test.dart
**READY**
Displays milliseconds appropriately when `progress` takes less than 100 milliseconds to complete like in this picture:
**Currently returns `0.0s` if less than 100ms.**
This is the sample code I've used in dart pad.
=> feat(logger): adds support for milliseconds on progress duration

.github/workflows/mason.yaml, .github/workflows/mason_cli.yaml, packages/mason/lib/src/compute.dart, packages/mason/lib/src/generator.dart, packages/mason/pubspec.yaml, packages/mason/test/src/generator_test.dart
**READY**
- fix(mason): use file descriptor pooling (closes #510)
=> fix(mason): use file descriptor pooling

packages/mason_logger/CHANGELOG.md, packages/mason_logger/README.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.3
=> chore(mason_logger): v0.1.3

packages/mason_api/lib/src/mason_api.dart, packages/mason_api/test/src/mason_api_test.dart
**READY**
- fix(mason_api): login sets in-memory credentials
=> fix(mason_api): login sets in-memory credentials

packages/mason_cli/lib/src/commands/add.dart, packages/mason_cli/test/commands/add_test.dart
**READY**
- feat(mason_cli): add <brick> <version>
=> feat(mason_cli): add <brick> <version>

packages/mason_logger/lib/mason_logger.dart, packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/lib/src/progress.dart, packages/mason_logger/test/src/mason_logger_test.dart, packages/mason_logger/test/src/progress_test.dart
**READY**
This PR addresses the open issue #451 
I have given the .progress API an optional value where developers can pass through their own array of strings they want to animate through.
If nothing is given, we will fall back to the original progressAnimation. 
Note: If the developer passes an empty array, this will break the logger (IntegerDivisionByZeroException). Do we want to check for this? Or should the developer just not pass through an empty array?
Let me know if there's anything that needs changing!
=> feat(mason_logger): add ProgressOptions API

packages/mason_logger/CHANGELOG.md, packages/mason_logger/LICENSE, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.1.4
=> chore(mason_logger): v0.1.4

packages/mason_cli/test/commands/make_test.dart, packages/mason_logger/example/main.dart, packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
Allows for `chooseAny` and `chooseOne` to receive a generic value and map it to string to display.
=> feat(mason_logger): generic support for `chooseOne` and `chooseAny`

packages/mason_logger/CHANGELOG.md, packages/mason_logger/example/main.dart, packages/mason_logger/pubspec.yaml, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- chore(mason_logger): v0.2.0
=> chore(mason_logger): v0.2.0

packages/mason_logger/CHANGELOG.md, packages/mason_logger/pubspec.yaml
**READY**
- chore(mason_logger): v0.2.1
=> chore(mason_logger): v0.2.1

packages/mason/lib/src/generator.dart, packages/mason/test/fixtures/empty/brick.yaml, packages/mason/test/src/generator_test.dart
**READY**
- fix(mason): allow optional __brick__ directory
=> fix(mason): allow optional __brick__ directory

packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.38
=> chore(mason): v0.1.0-dev.38

packages/mason_cli/lib/src/commands/search.dart, packages/mason_cli/test/commands/search_test.dart
**READY**
- feat(mason_cli): search separator length uses terminalColumns (closes #520)
=> feat(mason_cli): search separator length uses terminalColumns

.github/workflows/mason_cli.yaml, packages/mason/lib/mason.dart, packages/mason/lib/src/render.dart, packages/mason/lib/src/string_case_extensions.dart, packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/pubspec.yaml
**READY**
- feat(mason): export StringCaseExtensions (closes #645)
=> feat(mason): export StringCaseExtensions

bricks/widget/__brick__/{{name.snakeCase()}}.dart, packages/mason_cli/test/fixtures/add/widget/cat.dart, packages/mason_cli/test/fixtures/install/widget/cat.dart, packages/mason_cli/test/fixtures/make/widget/my_widget.dart
**READY**
Removed the super constructor and use `super.key` instead. At your command, sir. 🙌 👑
=> refactor: use `super.key`

packages/mason/lib/src/bricks_json.dart, packages/mason/test/src/generator_test.dart
**READY**
- fix(mason): git brick install across file systems (closes #828)
=> fix(mason): git brick install across file systems

packages/mason_logger/lib/src/progress.dart
**READY**
Related to #958 
Changes:
- Add pointers to documentation to other similar progress methods
Rationale:
The opposite of `fail` is `success`. However, the logger's API uses `fail` and `complete` instead. I imagine other developers will have the same issue and this addition will improve their experience by outlining this distinction.
=> docs(mason_logger): improve `Progress` documentation

extensions/vscode/CHANGELOG.md, extensions/vscode/LICENSE, extensions/vscode/package-lock.json, extensions/vscode/package.json, extensions/vscode/src/commands/make-brick.ts
**READY**
- chore(vscode): v0.1.11
=> chore(vscode): v0.1.11

packages/mason_cli/test/commands/make_test.dart
**READY**
Refactors the setup method of `make_test.dart`
Changes:
- Dynamically creates the content of mason.yaml and bricks.json
- Ensures `mason.yaml` and `bricks.json` are cleaned up (deleted)
=> test(mason_cli): refactor `setUp` in `make_test.dart`

packages/mason_cli/lib/src/commands/bundle.dart, packages/mason_cli/test/commands/bundle_test.dart
**READY FOR REVIEW**
Resolves #1213
=> feat(mason_cli): add `--set-exit-if-changed` for mason bundle

packages/mason_logger/lib/src/progress.dart, packages/mason_logger/test/src/progress_test.dart
**READY**
- closes https://github.com/felangel/mason/issues/1190
```dart
final progress = Logger().progress(
'Calculating',
options: const ProgressOptions(trailing: ' 🤔'),
);
```
```
⠴ Calculating 🤔 (0.4s)
```
=> feat(mason_logger): add `trailing` to `ProgressOptions`

packages/mason_logger/lib/src/ffi/windows_terminal.dart
**READY**
- refactor(mason_logger): remove deprecated methods in `WindowsTerminal`
=> refactor(mason_logger): remove deprecated methods in `WindowsTerminal`

packages/mason_logger/lib/src/mason_logger.dart, packages/mason_logger/test/src/mason_logger_test.dart
**READY**
- fix(mason_logger): throw `StateError` when prompting with no terminal attached
- Currently if mason_logger is used to prompt for input from a user in an environment with no terminal attached (e.g. CI), the process will hang indefinitely. This change adjusts the behavior to throw a `StateError` in order to make it clear that prompting for input should only be done in contexts where a terminal is attached.
=> fix(mason_logger): throw `StateError` when prompting with no terminal attached

packages/mason_cli/CHANGELOG.md, packages/mason_cli/LICENSE, packages/mason_cli/lib/src/version.dart, packages/mason_cli/pubspec.yaml
**READY**
- chore(mason_cli): v0.1.0-dev.54
=> chore(mason_cli): v0.1.0-dev.54

packages/mason/CHANGELOG.md, packages/mason/LICENSE, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason/test/src/bundler_test.dart, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0-dev.53
=> chore(mason): v0.1.0-dev.53

packages/mason_logger/lib/src/progress.dart, packages/mason_logger/test/src/progress_test.dart
Add Duration parameter to logger.progress() for customizable frame change speed
Ready
Added new parameter to the **ProgressAnimation** class to **control the speed of changing
between frames** because for me the default was so fast (80ms)
=> feat(mason_logger): add `interval` to `ProgressAnimation`

bricks/favorite_color/brick.yaml, bricks/favorite_languages/brick.yaml, bricks/flavors/brick.yaml, bricks/hello/brick.yaml, bricks/hooks/hooks/pubspec.yaml, bricks/random_color/hooks/pubspec.yaml, packages/mason/CHANGELOG.md, packages/mason/lib/src/version.dart, packages/mason/pubspec.yaml, packages/mason/test/bricks/loop/brick.yaml, packages/mason/test/bricks/nested_conditional/brick.yaml, packages/mason/test/src/bundler_test.dart, packages/mason_cli/README.md, packages/mason_cli/README.zh.md, packages/mason_cli/lib/src/commands/new.dart, packages/mason_cli/test/bricks/array_no_choices/brick.yaml, packages/mason_cli/test/bricks/enum_no_choices/brick.yaml, packages/mason_cli/test/commands/get_test.dart, packages/mason_cli/test/fixtures/new/custom/bricks/hello_world/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/brick.yaml, packages/mason_cli/test/fixtures/new/hooks/hooks/pubspec.yaml, packages/mason_cli/test/fixtures/new/simple/hello_world/brick.yaml
**READY**
- chore(mason): v0.1.0 (closes #1432)
=> chore(mason): v0.1.0
